import { Box, Heading, Flex } from '@chakra-ui/react'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import Banner from '../components/home/Banner'
import Blog from '../components/home/Blog'
import Contact from '../components/home/Contact'
import Education from '../components/home/Education'
import Experience from '../components/home/Experience'
import LeftSideBar from '../components/home/LeftSideBar'
import Recommendation from '../components/home/Recommendation'
import RightMenu from '../components/home/RightMenuBar'
import Services from '../components/home/Services'


export default function Home() {
  return (
    <Box w="full" h={['auto', "100vh"]} overflow={['auto', 'hidden']} bg="brand.grey" position="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w={['100%', "full"]} h="auto">
        <Box flex="0.2" bg="brand.white" h="100vh" overflow="auto" display={['none', 'block']} >
          <LeftSideBar />
        </Box>

        <Box flex={['1', "0.8"]} h="100vh" px={['0', "20px"]} overflow="auto">
          <Banner />
          <Services />
          <Recommendation />
          <Education />
          <Experience />
          <Blog />
          <Contact />
        </Box>

        <Box w="70px" h="100vh" bg="brand.white" display={['none', 'block']}>
          <RightMenu />
        </Box>
      </Flex>

    </Box>
  )
}
